# Use node 8.11.3 as the base image
FROM circleci/node:8.11.3

RUN sudo apt-get update \
    && sudo apt-get install lsb-release libappindicator3-1 curl libasound2 libnspr4 libnss3 libxss1 xdg-utils fonts-liberation \
    && sudo curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
    && sudo dpkg -i google-chrome.deb \
    && sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome \
    && sudo rm google-chrome.deb

RUN google-chrome --version 

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./frontend/package.json /usr/src/app/package.json
RUN npm install
RUN sudo npm install -g @angular/cli@1.7.1

# add app
COPY ./frontend /usr/src/app

# start app
CMD ng serve --host 0.0.0.0