# Use node 8.11.3 as the base image
FROM circleci/node:8.11.3-browsers

# set the work dir to /node
WORKDIR /usr/src/app
COPY ./frontend/package*.json /


# install http server to serve the static files
RUN sudo npm install -g superstatic

# set the workdir as the /app directory
# this dir is mapped to the frontend directory in the cloned repo
WORKDIR /app

# copy all files from frontend to app
COPY ./frontend /app

# install dependencies
USER root
RUN npm install
# install node-sass to fix error
RUN npm install node-sass

# Make port 4200 available to the world outside this container
EXPOSE 4200

# startup the angular server when the container launches
# build static files
RUN npm run build

# start server to serve static files at port 4200
CMD ["superstatic", "dist/", "-c", "superstatic.json", "--port", "4200", "--host", "0.0.0.0"]
