# Use node 6.11 as the base image
FROM node:6.11.1

WORKDIR /app

ADD server /app

# Make port 80 available to the world outside this container
EXPOSE 8080

# Run app.py when the container launches
CMD ["node", "app.es6"]
