# Use node 8.9.4 as the base image
FROM circleci/node:8.9.4-browsers

# set the work dir to /node
RUN sudo mkdir -p /node
COPY ./frontend/package.json /node
WORKDIR /node

# install the latest version of yarn
RUN sudo npm install yarn -g

# install http server to serve the static files
RUN sudo npm install -g superstatic


# change the node path env var to the new node_modules directory
# and add the new node .bin to the path
ENV NODE_PATH=/node/node_modules
ENV PATH=/node/node_modules/.bin:$PATH

# set the workdir as the /app directory
# this dir is mapped to the frontend directory in the cloned repo
WORKDIR /app

# copy all files from frontend to app
COPY ./frontend /app

# install dependencies
RUN sudo yarn
# install node-sass to fix error
RUN sudo yarn add node-sass

# Make port 4200 available to the world outside this container
EXPOSE 4200

# startup the angular server when the container launches
# build static files
RUN sudo yarn run build

# start server to serve static files at port 4200
CMD ["superstatic", "dist/", "-c", "superstatic.json", "--port", "4200", "--host", "0.0.0.0"]
