const forests = [
    {
      id: 1,
      forest_name: 'Idaho Panhandle National Forest',
      forest_url: 'https://www.fs.usda.gov/ipnf/',
      start_date: '2019-11-18T08:00:00Z',
      end_date: '2019-12-25T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'Idaho Panhandle | Idaho',
      forest_abbr: 'ipnf',
      wood_cost: 5,
      timezone: 'America/Boise',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '{ "Idaho Panhandle Supervisors Office": {"address": "3815 Schreiber Way", "citystate": "Coeur d AudioListener, ID", "phone": "(208) 765-7223"},',
      poss_financial_id: '',
      state: 'Idaho',
      permit_type: 'fuel',
      region: 1
    },
    {
      id: 2,
      forest_name: 'Flathead National Forest',
      forest_url: 'https://www.fs.usda.gov/flathead/',
      start_date: '2020-04-01T08:00:00Z',
      end_date: '2021-03-31T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'Flathead | Montana',
      forest_abbr: 'flathead',
      wood_cost: 5,
      timezone: 'America/Boise',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '{ "Flathead Supervisors Office / Tally Lake Ranger District": {"address": "650 Wolfpack Way", "citystate": "Kalispell, Montana", "phone": "(406) 758-5204"},',
      poss_financial_id: '',
      state: 'Montana',
      permit_type: 'fuel',
      region: 1
    },
    {
      id: 3,
      forest_name: 'Chattahoochee-Oconee National Forest',
      forest_url: 'https://www.fs.usda.gov/conf',
      start_date: '2020-01-01T08:00:00Z',
      end_date: '2021-12-31T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'Chattahoochee-Oconee | Georgia',
      forest_abbr: 'conf',
      wood_cost: 5,
      timezone: 'America/Detroit',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '',
      poss_financial_id: '',
      state: 'Georgia',
      permit_type: 'fuel',
      region: 8
    },
    {
      id: 4,
      forest_name: 'George Washington & Jefferson National Forest',
      forest_url: 'https://www.fs.usda.gov/gwj',
      start_date: '2020-01-01T08:00:00Z',
      end_date: '2021-12-31T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'George Washington & Jefferson | Virginia',
      forest_abbr: 'gwj',
      wood_cost: 6,
      timezone: 'America/Detroit',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '',
      poss_financial_id: '',
      state: 'Virginia',
      permit_type: 'fuel',
      region: 8
    },
    {
      id: 5,
      forest_name: 'Shoshone National Forest',
      forest_url: 'https://www.fs.usda.gov/shoshone',
      start_date: '2020-01-01T08:00:00Z',
      end_date: '2021-12-31T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'Shoshone | Wyoming',
      forest_abbr: 'shoshone',
      wood_cost: 7.5,
      timezone: 'America/Boise',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '',
      poss_financial_id: '',
      state: 'Wyoming',
      permit_type: 'fuel',
      region: 2
    },
    {
      id: 6,
      forest_name: 'Hiawatha National Forest',
      forest_url: 'https://www.fs.usda.gov/hiawatha',
      start_date: '2020-01-01T08:00:00Z',
      end_date: '2021-12-31T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'Hiawatha | Michigan',
      forest_abbr: 'hiawatha',
      wood_cost: 5,
      timezone: 'America/Detroit',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '',
      poss_financial_id: '',
      state: 'Michigan',
      permit_type: 'fuel',
      region: 9
    },
    {
      id: 7,
      forest_name: 'Grand Mesa Uncompahgre & Gunnison National Forest',
      forest_url: 'https://www.fs.usda.gov/gmug',
      start_date: '2020-01-01T08:00:00Z',
      end_date: '2021-12-31T08:59:59Z',
      created: 'now()',
      updated: 'now()',
      org_structure_code: '',
      description: 'Grand Mesa Uncompahgre and Gunnison | Colorado',
      forest_abbr: 'gmug',
      wood_cost: 5,
      timezone: 'America/Boise',
      cutting_areas: '{}',
      map_links: '{}',
      contact:
      '',
      poss_financial_id: '',
      state: 'Colorado',
      permit_type: 'fuel',
      region: 2
    }
  ];
  module.exports = {
    up(queryInterface) {
      return queryInterface.bulkInsert('fsForests', forests);
    },
    down(queryInterface) {
      return queryInterface.bulkDelete('fsForests');
    }
  };
