export const tempOutfitterMock = {
  appControlNumber: '222',
  applicationId: '',
  createdAt: '',
  applicantMessage: '',
  status: '',
  authEmail: '',
  revisions: '',
  district: '11',
  region: '06',
  forest: '05',
  type: 'temp-outfitter',
  signature: '',
  authorizingOfficerName: '',
  authorizingOfficerTitle: '',
  applicantInfo: {
    addAdditionalPhone: '',
    emailAddress: '',
    organizationName: '',
    primaryFirstName: '',
    primaryLastName: '',
    orgType: '',
    website: '',
    goodStandingEvidence: ''
  },
  additionalInfo: '',
  guideIdentification: '',
  operatingPlan: '',
  liabilityInsurance: '',
  acknowledgementOfRisk: '',
  locationMap: '',
  tempOutfitterFields: {
    additionalInfoDescription: '',
    individualIsCitizen: '',
    smallBusiness: '',
    advertisingDescription: '',
    advertisingURL: '',
    noPromotionalWebsite: '',
    clientCharges: '',
    experienceList: ''
  }
};
